name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client-sdk-android
    steps:
    - name: checkout client-sdk-android
      uses: actions/checkout@v2.3.4
    - name: checkout protocol
      uses: actions/checkout@v2.3.4
      with:
        repository: livekit/protocol
    - name: set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: |
        pwd
        ls
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        pwd
        ls
        ./gradlew assemble
